services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: lumigiabot
    restart: always
    volumes:
      - ./data:/app/data
    env_file: .env
    depends_on:
      - web
    networks:
      - lumigiabot-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: lumigiabot-web
    restart: always
    ports:
      - "3412:3412"
    volumes:
      - ./data:/app/data
    env_file: .env
    networks:
      - lumigiabot-network

networks:
  lumigiabot-network:
    driver: bridge
